path = "~/Music/hanabie"

videos = [
  "https://www.youtube.com/watch?v=vdZFDaCjQ0w",
  "https://www.youtube.com/watch?v=Awx5vfb_aSY",
  "https://www.youtube.com/watch?v=fuFbQ-Mewfw",
  "https://www.youtube.com/watch?v=hTuPwVYHc_M",
  "https://www.youtube.com/watch?v=B9cC2_V7JwE",
  "https://www.youtube.com/watch?v=nSvhK9U2BXk",
  "https://www.youtube.com/watch?v=SPSpXzp3tfQ",
]
