path = "~/Music/sabaton"


videos = [
  "https://www.youtube.com/watch?v=gtbbIB776ks",
  "https://www.youtube.com/watch?v=rM9PuJxppdI",
  "https://www.youtube.com/watch?v=m-yrjYF3I8U&t=3s",
  "https://www.youtube.com/watch?v=OgLdEKnHD2Y",
  "https://www.youtube.com/watch?v=OgLdEKnHD2Y",
]
